apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: journal-dev
type: Opaque
stringData:
  APPLICATION_JWT_SECRETKEY: a8a94ef93e45005ade280b65db44fb7e835405ef1ab4ee5da0ddfa17fdc55eeb42f2b87f