apiVersion: v1
kind: Service
metadata:
  name: journal-api
  namespace: journal-dev
  labels:
    app: journal-api
spec:
  type: LoadBalancer
  selector:
    app: journal-api
  ports:
  - name: http
    port: 80
    targetPort: 8080