apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: journal-dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: somerandomrootpassword
  MYSQL_USER: journal_app
  MYSQL_PASSWORD: somerandompassword
  MYSQL_DATABASE: journal