apiVersion: v1
kind: Secret
metadata:
  name: {{ include "journal.fullname" . }}-secret
  labels:
    {{- include "journal.labels" . | nindent 4 }}
type: Opaque
stringData:
  APPLICATION_JWT_SECRETKEY: {{ .Values.jwt.secret | quote }}
